### ISSUE TITLE
fitting of unsupervised models fails

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJScikitLearnInterface.jl#10]
<pre><font color="#586E75"><b>julia&gt; </b></font>X, _ = make_blobs(500, 3, rng=555)
(Tables.MatrixTable{Array{Float64,2}}: (x1 = [-0.14776259415495518, -1.123245706746543, ... 

<font color="#586E75"><b>julia&gt; </b></font>m = AgglomerativeClustering()
AgglomerativeClustering(
    n_clusters = 2,
    affinity = &quot;euclidean&quot;,
    memory = nothing,
    connectivity = nothing,
    compute_full_tree = &quot;auto&quot;,
    linkage = &quot;ward&quot;,
    distance_threshold = nothing)<font color="#268BD2"> @ 2…22</font>

<font color="#586E75"><b>julia&gt; </b></font>using MLJBase

<font color="#586E75"><b>julia&gt; </b></font>f, = MLJBase.fit(m, 1, X)
<font color="#CB4B16"><b>ERROR: </b></font><font color="#CB4B16">MethodError: objects of type Tuple{Symbol,Symbol,Symbol} are not callable</font>
Stacktrace:
 [1] <b>fit(</b><b>::AgglomerativeClustering, ::Int64, ::Tables.MatrixTable{Array{Float64,</b>2}}<b>)</b> at <b>/home/okonsamuel/.julia/packages/MLJScikitLearnInterface/0IUeM/src/macros.jl:249</b>
 [2] top-level scope at <b>REPL[119]:1</b>

</pre>

**Comment by tlienart** [comment]
closed by #11
