### ISSUE TITLE
`_process_model_def` takes two arguments instead of one

### ISSUE THREAD

**Issue by HamletWantToCode** [alan-turing-institute/MLJScikitLearnInterface.jl#18]
Hi, thank you for providing `MLJ`, it's really a great package !

I'm currently implement an algorithm that needs `ScikitLearn.jl` as backend. However, when I called `@load GaussianProcessRegressor`, I got the following error:
```julia
julia> using MLJ
julia> @load GaussianProcessRegressor
[ Info: Precompiling MLJScikitLearnInterface [5ae90465-5518-4432-b9d2-8a1def2f0cab]
ERROR: LoadError: LoadError: LoadError: MethodError: no method matching _process_model_def(::Expr)
Closest candidates are:
  _process_model_def(::Any, ::Any) at /Users/hongbin/.julia/packages/MLJModelInterface/40CQ6/src/model_def.jl:26
```

After a quick bit of digging it seems it is due to here:
https://github.com/alan-turing-institute/MLJScikitLearnInterface.jl/blob/2141fe92519ecb7e9831ae04308bbfd0c6998257/src/macros.jl#L58

While the definition of `_process_model_def` [here](https://github.com/alan-turing-institute/MLJModelInterface.jl/blob/8469bd919eeeab084e7cf5a726e838fcd34010fd/src/model_def.jl#L26) takes two arguments.

I'm under:
```julia
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, ivybridge)
Environment:
  JULIA_NUM_THREADS = 10
```
all packages are up to date.

**Comment by OkonSamuel** [comment]
@HamletWantToCode Thanks for using MLJ.
I just opened a PR that would close this issue.

**Comment by HamletWantToCode** [comment]
Thanks, it seems that the PR hasn't been merged. But I'll close this issue anyway.

**Comment by ablaom** [comment]
https://github.com/JuliaRegistries/General/pull/23195 should fix this
