### ISSUE TITLE
no method matching _process_model_def(::Expr) when importing

### ISSUE THREAD

**Issue by Fabien-00** [alan-turing-institute/MLJScikitLearnInterface.jl#21]
Can't import MLJScikitLearnInterface ,
`ERROR: LoadError: LoadError: LoadError: MethodError: no method matching _process_model_def(::Expr)`

Just add MLJ and MLJScikitLearnInterface and try to import MLJScikitLearnInterface to recreate the error .

Version : 
```
[[MLJ]]
deps = ["CategoricalArrays", "ComputationalResources", "Distributed", "Distributions", "LinearAlgebra", "MLJBase", "MLJModels", "MLJScientificTypes", "MLJTuning", "Pkg", "ProgressMeter", "Random", "Statistics", "StatsBase", "Tables"]
git-tree-sha1 = "f807e3342ce84b71bdd12aaa86060c76b59e5e1c"
uuid = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
version = "0.14.0"

[[MLJScikitLearnInterface]]
deps = ["MLJModelInterface", "PyCall", "ScikitLearn"]
git-tree-sha1 = "9202b249509ec05fd8a5e71b278f42b491f4f324"
uuid = "5ae90465-5518-4432-b9d2-8a1def2f0cab"
version = "0.1.5"
```

**Comment by ablaom** [comment]
Thanks for reporting! Known issue. https://github.com/alan-turing-institute/MLJScikitLearnInterface.jl/issues/18
Working on this now.

**Comment by ablaom** [comment]
https://github.com/JuliaRegistries/General/pull/23195

**Comment by Fabien-00** [comment]
Thank you for fixing it fast , 
but right now i have an error when trying to load a model i saved before that use MLJScikitlearn

i get this error :
```
[warn | JLSO]: EOFError: read end of file
ERROR: MethodError: no method matching Machine(::Array{UInt8,1})
```

When doing :
`machine("pathtothefile")`

I'm not 100% sure it's from the 1.6.0 but i didn't change anything so it should be , the file exists 
i get true if i do
`isfile("pathtothefile")`

Thank you

**Comment by ablaom** [comment]
Okay. This looks serious. I will investigate.

**Comment by ablaom** [comment]
Okay, maybe not so serious as I first thought (I was looking at an old branch of MLJBase). 

It's possible that https://github.com/alan-turing-institute/MLJBase.jl/pull/429 broke something, but I can't see what.

1. Are you able to do this: `using JLSO;     dict = JLSO.load("pathtofile")` ? If so, what do you get for `keys(dict)` and for the types of the values?

2. What sk-learn model are you using?

**Comment by Fabien-00** [comment]
1.
No same error 
2.
pkg="ScikitLearn", "RandomForestClassifier"

**Comment by Fabien-00** [comment]
Hey , after the last update you did , i can do JLSO.load on the model but i still can't do machine(path)
Also is there a way to load the machine() with this jlso.load ? it return me a dict with weights and informations but i don't know how to bind it with a machine()

Thank you

**Comment by OkonSamuel** [comment]
```julia
dict = JLSO.load("pathtothefile")
model, fitresult, report = dict[:model], dict[:fitresult], dict[:report]
 mach = Machine(model)
 mach.fitresult = fitresult
 mach.state = 1
 mach.report = report
```
i would suggest re-saving your model in new MLJ version.

**Comment by Fabien-00** [comment]
I actually tried to do 
```
mach = Machine(dict[:model])
```
but i get :
```
ERROR: MethodError: no method matching Machine(::Array{UInt8,1})
```

**Comment by ablaom** [comment]
@FabienGadet0 You are sure you have loaded the same code before restoring the machine (ie done `@load RandomForestClassifier pkg=ScikitLearn`)? The `Array{UInt8,1}` objects will appear when JLSO fails to find appropriate julia objects. Eg:

```julia
using MLJ

model = @load RandomForestClassifier pkg=ScikitLearn

data = load_iris()
y, X = unpack(data, ==(:target), n->true, rng=1234)

mach = machine(model, X, y) |> fit!
MLJ.save("junk.jlso", mach)

## NEW REPL SESSION

julia> JLSO.load("junk.jlso")
[warn | JLSO]: KeyError: key MLJScikitLearnInterface [5ae90465-5518-4432-b9d2-8a1def2f0cab] not found
[warn | JLSO]: KeyError: key PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0] not found
Dict{Symbol,Any} with 3 entries:
  :fitresult => UInt8[0x37, 0x4a, 0x4c, 0x0a, 0x04, 0x00, 0x00, 0x00, 0x14, 0x0…
  :report    => NamedTuple()
  :model     => UInt8[0x37, 0x4a, 0x4c, 0x0a, 0x04, 0x00, 0x00, 0x00, 0x35, 0x1…
```

In any case, I am experiencing some intermittent problems restoring scikitlearn models https://github.com/alan-turing-institute/MLJBase.jl/issues/435

@FabienGadet0 As a temporary measure, you may want to consider RandomForestClassifier from DecisionTrees.jl - a pure Julia implementation, if that provides what you need.

**Comment by Fabien-00** [comment]
JLSO didn't give me any hint that he didn't load it well so i don't know . 
I'll take a look at DecisionTree.jl ok thank you
