### ISSUE TITLE
Problem installing python scikit-learn in CI

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJScikitLearnInterface.jl#42]
Some change unrelated to this package is now causing CI to fail (triggered CI with a trivial commit):

https://github.com/JuliaAI/MLJScikitLearnInterface.jl/runs/7666259538?check_suite_focus=true

@OkonSamuel

**Comment by OkonSamuel** [comment]
Caused by outdated julia version of some linux libraries. See https://github.com/JuliaLang/julia/issues/46345
