### ISSUE TITLE
Support Array API

### ISSUE THREAD

**Issue by tylerjthomas9** [alan-turing-institute/MLJScikitLearnInterface.jl#66]
https://scikit-learn.org/stable/modules/array_api.html#array-api

It is worth adding support for training with the Array API if the Python packages are available in the environment.

**Comment by ablaom** [comment]
Thanks for flagging @tylerjthomas9 . 

From sk-learn:

> At this stage, this support is considered experimental and must be enabled explicitly as explained in the following.

This suggests to me that adding support here could also add a maintenance burden. I'd rather divert energies into Julia solutions. And julia already has great array support 😉 . 

I certainly wouldn't object to adding this, so long as its also clearly flagged as experimental. But I'm not going to be much help supporting the addition.

**Comment by tylerjthomas9** [comment]
That's a good point. The main reason that it interests me is easy GPU (and I think multi-GPU) training for the models that support it, but we definitely have to wait for it to be stable.
